# Generated by Django 4.2.7 on 2023-11-27 10:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='название группы видео', max_length=50, verbose_name='Название группы')),
                ('slug', models.SlugField(help_text='slug группы', max_length=20, unique=True, verbose_name='Уникальный slug')),
                ('description', models.TextField(help_text='Описание группы', max_length=200, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Статус просмотра видео', max_length=50, unique=True, verbose_name='Статус')),
                ('color', models.CharField(choices=[('#008000', 'зеленый'), ('#FF9900', 'оранжевый'), ('#f44336', 'красный')], help_text='Цвет в формате HEX', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Цвет толжен быть в формате HEX!', regex='#[A-F\\d]{6}')], verbose_name='Цвет статуса')),
                ('slug', models.SlugField(help_text='уникальный слаг статуса до 100 символов', max_length=100, unique=True, verbose_name='Слаг статуса')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='название видео', max_length=50, verbose_name='название')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Дата публикации в формате "ДД название месяца ГГГГ"', verbose_name='Дата публикации')),
                ('description', models.CharField(help_text='описание видео', max_length=200, verbose_name='описание')),
                ('video', models.FileField(help_text='видеофайл', unique=True, upload_to='video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('MOV', 'avi', 'mp4', 'webm', 'mkv'), code='неверное расширение')], verbose_name='Видеозапись')),
                ('image', models.ImageField(blank=True, help_text='Изображение поста', upload_to='posts/', verbose_name='Картинка')),
                ('author', models.ForeignKey(help_text='Сотрудник загрузивший видео', on_delete=django.db.models.deletion.DO_NOTHING, related_name='videos', to=settings.AUTH_USER_MODEL, verbose_name='автор видео')),
                ('group', models.ForeignKey(help_text='группа видео', on_delete=django.db.models.deletion.DO_NOTHING, to='video.group', verbose_name='группа')),
                ('status', models.ForeignKey(help_text='статус видео', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='video.status', verbose_name='статус')),
            ],
            options={
                'verbose_name': 'Видеозапись',
                'verbose_name_plural': 'Видеозаписи',
            },
        ),
    ]
