# Generated by Django 4.2.7 on 2023-11-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение поста', upload_to='video/', verbose_name='Картинка'),
        ),
    ]
