# Generated by Django 4.2.7 on 2024-07-15 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_video_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Видеозапись', 'verbose_name_plural': 'Видеозаписи'},
        ),
    ]
