# Generated by Django 4.2.7 on 2024-01-29 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video', '0002_alter_video_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Номер замечания из чек-листа', max_length=6, unique=True, verbose_name='Номер замечания')),
                ('personnel_action', models.TextField(help_text='Описание замечания из чек-листа', max_length=500, unique=True, verbose_name='Описание замечания')),
                ('value', models.BooleanField(help_text='Оценка действий персонала по чек-листу', verbose_name='Оценка действий ДА/НЕТ')),
                ('description', models.TextField(help_text='Описание нарушений/замечаний по действиям персонала', max_length=500, verbose_name='Краткое описание нарушений/замечаний')),
            ],
            options={
                'verbose_name': 'Действие персонала',
                'verbose_name_plural': 'Действия персонала',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название чек-листа проверки видео', max_length=50, unique=True, verbose_name='Название чек-листа')),
                ('structural_subdivision', models.CharField(choices=[('ПрЭО "Холмогорнефть"', 'ХН'), ('ПрЭО "Муравленковскнефть"', 'МН'), ('ПрЭО "Приобскнефть"', 'ПН'), ('ПО "Оренбургнефть"', 'ОН'), ('ПрЭО "Востокнефть"', 'ВН'), ('ПрЭО "Ямал"', 'Ямал'), ('ПрЭО "Тюмень"', 'Тюмень')], help_text='Название подразделения', max_length=50, verbose_name='Название ПрЭО/ПО')),
                ('working_place', models.CharField(help_text='Место производства работ', max_length=100, verbose_name='Рабочее место')),
                ('record_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата записи видео', verbose_name='Дата видео')),
                ('bp_number', models.CharField(help_text='Номер бланка переключений с описанием', max_length=100, verbose_name='Номер бланка переключений')),
                ('working_person', models.CharField(help_text='Лицо непосредственно производящее переключение', max_length=100, verbose_name='Лицо производящее переключение')),
                ('controlling_person', models.CharField(help_text='Лицо непосредственно производящее переключение', max_length=100, verbose_name='Лицо производящее переключение')),
                ('recording_quality', models.CharField(choices=[('Хорошее качество видео/звука', 'Хорошее'), ('Удовлетворительное качество видео/звука', 'Удовлетворительное'), ('Плохое качество видео/звука', 'Плохое')], help_text='Качество видеозаписи (картинка, звук)', max_length=50, verbose_name='Качество видео')),
                ('brif_conclusion', models.TextField(help_text='Краткий вывод о произведенной проверке видео', max_length=500, verbose_name='Краткий вывод о проверке')),
                ('offer', models.TextField(help_text='Предложения по результату проверки', max_length=500, verbose_name='Предложение')),
                ('inspector', models.ForeignKey(help_text='Лицо заполняющее чек-лист', on_delete=django.db.models.deletion.DO_NOTHING, related_name='check_list', to=settings.AUTH_USER_MODEL, verbose_name='Проверяющий')),
                ('personnel_actions', models.ManyToManyField(help_text='Действия персонала, к котором относится чек-лист', related_name='+', to='check_list.personnelactions', verbose_name='Действия персонала')),
                ('video', models.ForeignKey(help_text='Видео, к которому относится чек-лист', on_delete=django.db.models.deletion.CASCADE, related_name='check_lists', to='video.video', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Чек лист',
                'verbose_name_plural': 'Чек листы',
                'ordering': ('id',),
            },
        ),
    ]
