# Generated by Django 4.2.7 on 2024-01-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelactions',
            name='description',
            field=models.TextField(default='-', help_text='Описание нарушений/замечаний по действиям персонала', max_length=500, verbose_name='Краткое описание нарушений/замечаний'),
        ),
    ]
