# Generated by Django 4.2.7 on 2024-01-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_list', '0002_alter_personnelactions_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='personnel_actions',
            field=models.ManyToManyField(help_text='Действия персонала, к котором относится чек-лист', related_name='personnel_actions', to='check_list.personnelactions', verbose_name='Действия персонала'),
        ),
    ]
