# Generated by Django 4.2.7 on 2024-01-30 07:25

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('check_list', '0003_alter_checklist_personnel_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='personnel_actions',
            field=models.ManyToManyField(help_text='Действия персонала, к котором относится чек-лист', related_name='+', to='check_list.personnelactions', verbose_name='Действия персонала'),
        ),
        migrations.CreateModel(
            name='PersonnelActionsValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('ДА', 'Да'), ('НЕТ', 'Нет')], help_text='Выбор из значений ДА/НЕТ', max_length=3, verbose_name='Отметка действия')),
                ('description', models.CharField(help_text='Краткое описание действия', max_length=500, verbose_name='Описание действия')),
                ('check_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_list.checklist')),
                ('personnel_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_list.personnelactions')),
            ],
            options={
                'verbose_name': 'пункт в акте',
                'verbose_name_plural': 'пункты в актах',
                'ordering': (builtins.id,),
            },
        ),
    ]
