# Generated by Django 4.2.7 on 2024-01-30 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_list', '0004_alter_checklist_personnel_actions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnelactionsvalue',
            options={'ordering': ('id',), 'verbose_name': 'пункт в акте', 'verbose_name_plural': 'пункты в актах'},
        ),
    ]
