# Generated by Django 4.2.7 on 2024-01-30 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_list', '0005_alter_personnelactionsvalue_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnelactions',
            name='description',
        ),
        migrations.RemoveField(
            model_name='personnelactions',
            name='value',
        ),
    ]
