# Generated by Django 4.2.7 on 2024-01-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_list', '0006_remove_personnelactions_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='personnel_actions',
            new_name='personnel_actions_dict',
        ),
        migrations.RenameField(
            model_name='personnelactions',
            old_name='personnel_action',
            new_name='personnel_action_description',
        ),
        migrations.AlterField(
            model_name='checklist',
            name='controlling_person',
            field=models.CharField(help_text='Лицо непосредственно контролирующее переключение', max_length=100, verbose_name='Лицо контролирующее переключение'),
        ),
    ]
