# Generated by Django 4.2.7 on 2024-02-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_list', '0008_remove_checklist_personnel_actions_dict'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnelactionsvalue',
            options={'ordering': ('id',), 'verbose_name': 'пункт в чек-листе', 'verbose_name_plural': 'пункты в чек-листах'},
        ),
        migrations.AlterField(
            model_name='personnelactionsvalue',
            name='description',
            field=models.CharField(blank=True, help_text='Краткое описание действия', max_length=500, verbose_name='Описание действия'),
        ),
        migrations.AlterField(
            model_name='personnelactionsvalue',
            name='value',
            field=models.CharField(blank=True, choices=[('ДА', 'Да'), ('НЕТ', 'Нет')], help_text='Выбор из значений ДА/НЕТ', max_length=3, verbose_name='Отметка действия'),
        ),
    ]
